### ISSUE TITLE
Use stock license

### ISSUE THREAD

**Issue by nitrocode** [domain-protect/terraform-aws-domain-protect#28]
I noticed the license says Apache License 2.0 but doesn't contain all the text

https://github.com/domain-protect/terraform-aws-domain-protect/blob/main/LICENSE.md

Could we change the license to the official AL2 text ?

https://github.com/apache/.github/blob/main/LICENSE

**Comment by paulschwarzenberger** [comment]
Yes, there's no reason not to use the official one
