### ISSUE TITLE
Enable renovatebot in the repo

### ISSUE THREAD

**Issue by nitrocode** [domain-protect/terraform-aws-domain-protect#4]
https://github.com/apps/renovate

It's a lot better than dependabot, more configurable, and it detects most dependencies out of the box.

If it's decided to install this, then let's install it for the org and then centralize configs in an empty repo `domain-protect/renovate-configs`.

**Comment by paulschwarzenberger** [comment]
this looks very interesting, I'll get an opinion from someone else within OWASP to see whether they have any comments

**Comment by paulschwarzenberger** [comment]
This looks good to me, it's a very popular repo which appears to be well maintained with a large number of contributors. I'm happy to go ahead with this.

**Comment by nitrocode** [comment]
Wonderful. Could you install the app in the domain-protect org but maybe only include this repo so we don't need to deal with duplicate PRs. That should be enough to send the onboarding PR to get started

**Comment by paulschwarzenberger** [comment]
That's now installed as suggested
