### ISSUE TITLE
CODEOWNER errors

### ISSUE THREAD

**Issue by nitrocode** [domain-protect/terraform-aws-domain-protect#5]
It's probably missing the team

https://github.com/domain-protect/terraform-aws-domain-protect/blob/main/.github/CODEOWNERS

**Comment by paulschwarzenberger** [comment]
yes, that's correct - this is historic!

**Comment by nitrocode** [comment]
Could you add @domain-protect/admins or a similar team to the repo? Then we can keep the CODEOWNERS file the same or modify it to match the team.

**Comment by paulschwarzenberger** [comment]
@nitrocode thanks for the prompt - just added
